steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/fastpath-go:$SHORT_SHA'
  - '.'
  - '-f'
  - 'docker/application/Dockerfile'
  timeout: '1800s'

- name: 'gcr.io/cloud-builders/docker'
  id: Push image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/fastpath-go:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: Tag as latest
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/fastpath-go:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/fastpath-go:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: Push latest
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/fastpath-go:latest'
timeout: '2400s'