steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build nff-go builder image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/nff-go-builder:latest'
  - '.'
  - '-f'
  - 'docker/nff-go-builder/Dockerfile'
  timeout: '1800s'

- name: 'gcr.io/cloud-builders/docker'
  id: Push image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME/nff-go-builder:latest'

timeout: '2400s'